app/urls.py
from django.urls import path
from .views import *

app_name = 'app'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('signup/', user_signup, name='signup'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', user_logout, name='logout'),
    path('upload/', InitiateUpload.as_view(), name = 'file_upload_initiate'),
    path('upload/<int:file_id>/', UploadAudio.as_view(), name = 'file_upload'),
    #path('initiateProcessing/', initiate_processing, name='initiate_processing')
]

metasud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

class SystemUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    associated_respeaker_token = models.CharField(max_length = 32, blank=True, null = True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class AudioFile(models.Model):
    file = models.FileField(blank=True, null=True, upload_to='uploads/')
    file_name = models.CharField(max_length = 120)
    size = models.CharField(max_length = 10)
    duration = models.CharField(max_length = 10)
    user = models.ForeignKey(SystemUser, on_delete = models.CASCADE, null=True)
    def __str__(self):
        return self.file_name



class Speaker(models.Model): 
    first_name = models.CharField(max_length = 30, null = False, blank = False)
    last_name = models.CharField(max_length = 30, null = False, blank = False)
    user = models.ForeignKey(SystemUser, on_delete = models.CASCADE)
    voice_sample = models.OneToOneField(AudioFile, on_delete = models.SET_NULL, null = True)
    embeddings = models.TextField(blank=True, null = True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Meeting(models.Model):
    name = models.CharField(max_length = 128)
    date_time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(SystemUser, on_delete = models.CASCADE)
    audio_file = models.ForeignKey(AudioFile, on_delete = models.SET_NULL, null = True)
    speakers = models.ManyToManyField(Speaker)
    transcript_file = models.TextField(blank=True, null = True)
    summary_file = models.TextField(blank=True, null = True)

    def __str__(self):
        return self.name





app/templates/app/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Congrats, you made it in!</h1>
</body>
</html>

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="POST" action="{% url 'app:login' %}">
        {% csrf_token %} 
        <input type="text" name="username" id="" value="{{ username }}">
        <input type="password" name="password" id="">
        <input type="submit" value="Login">
    </form>
</body>
</html>

app/templates/app/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="POST" action="{% url 'app:signup' %}">
        {% csrf_token %} 
        <input type="email" name="email" id="">
        <input type="text" name="username" id="">
        <input type="password" name="password" id="">
        <input type="submit" value="Sign Up">
        <div>{{ error }}</div>
    </form>
</body>
</html>